# docker-compose.yaml
version: '3.8'

services:
  web:
    build: .
    command: 
      bash -c './reset_db.sh &&
      python manage.py runserver 0.0.0.0:8001'
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - .env
