# このYAMLファイルは、GitHub Actionsのワークフロー定義で、新しいリリースが公開されたときに自動的にプロダクション環境へのデプロイを行います。

name: Deploy to AWS  # ワークフローの名前を定義します。

on:  # このワークフローがトリガーされるイベントを定義します。
  push:  # pushイベントがトリガーとなります。
    branches:
      - master  # masterブランチへのpushでワークフローが開始されます。

jobs:  # ワークフロー内で実行されるジョブを定義します。
  deploy:  # ジョブの名前を定義します。
    runs-on:  # ジョブが実行されるランナーを定義します。
      - self-hosted  # 自己ホスト型のランナーを使用します。
    env:  # ジョブで使用される環境変数を定義します。
      ENVIRONMENT: test  # 環境名を定義します。
    steps:  # ジョブ内で実行されるステップを定義します。
      - name: Checkout  # ステップの名前を定義します。
        uses: actions/checkout@v4  # GitHubのリポジトリをチェックアウトします。
      - run: docker compose -f docker-compose.yml build  # Docker Composeを使用してアプリケーションをビルドします。
      - run: docker compose -f docker-compose.yml up -d  # Docker Composeを使用してアプリケーションを起動します。
